version: '3.1'

services:
    mailhog:
        image: mailhog/mailhog
        container_name: "mailhog"
        ports:
            - "${MAILHOG_SMTP_PORT:-1025}:1025"
            - "${MAILHOG_UI_PORT:-8025}:8025"
        restart: always
        networks:
            - mailhog-net

networks:
    mailhog-net:
        external: true
