services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "${JAEGER_UI_PORT:-16686}:16686"
      - "${JAEGER_OTLP_HTTP_PORT:-4318}:4318"
    environment:
      TZ: Asia/Shanghai
      SPAN_STORAGE_TYPE: badger
      BADGER_EPHEMERAL: "false"
      BADGER_DIRECTORY_VALUE: /badger/data
      BADGER_DIRECTORY_KEY: /badger/key
    volumes:
      - ./data:/badger
    restart: always
    networks:
      - jaeger-net

networks:
  jaeger-net:
    external: true
