services:
  rabbitmq:
    restart: always
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - ${RABBITMQ_PORT:-5672}:5672
      - ${RABBITMQ_UI_PORT:-15672}:15672
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-nilsir}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-nilsir}
    volumes:
      - ./data:/var/lib/rabbitmq
      - ./plugins/rabbitmq_delayed_message_exchange-4.0.2.ez:/plugins/rabbitmq_delayed_message_exchange-4.0.2.ez
    entrypoint: ["/bin/sh", "-c", "rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange && rabbitmq-server"]
    networks:
      - rabbitmq-net
networks:
    rabbitmq-net:
        external: true
