version: '3.7'

services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - ${UI_PORT:-8500}:8500  # Consul UI
      - 8600:8600/udp  # DNS
      - 8300:8300
      - 8301:8301
      - 8302:8302
    command: "agent -dev -client=0.0.0.0"
    volumes:
      - ./data:/consul/data
    networks:
      - consul-net
    restart: always

networks:
  consul-net:
    external: true
