version: '3.7'

services:
  consul-server1:
    image: hashicorp/consul:latest
    container_name: consul-server1
    ports:
      - ${SERVER1_UI_PORT:-8501}:8500
      - 8601:8600/udp
      - 8301:8300
    command: "agent -server -bootstrap-expect=3 -node=server1 -client=0.0.0.0 -ui -retry-join=consul-server2 -retry-join=consul-server3"
    volumes:
      - ./data/data1:/consul/data
    networks:
      - consul-net
    restart: always

  consul-server2:
    image: hashicorp/consul:latest
    container_name: consul-server2
    ports:
      - ${SERVER2_UI_PORT:-8502}:8500
      - 8602:8600/udp
      - 8302:8300
    command: "agent -server -bootstrap-expect=3 -node=server2 -client=0.0.0.0 -ui -retry-join=consul-server1 -retry-join=consul-server3"
    volumes:
      - ./data/data2:/consul/data
    networks:
      - consul-net
    restart: always

  consul-server3:
    image: hashicorp/consul:latest
    container_name: consul-server3
    ports:
      - ${SERVER3_UI_PORT:-8503}:8500
      - 8603:8600/udp
      - 8303:8300
    command: "agent -server -bootstrap-expect=3 -node=server3 -client=0.0.0.0 -ui -retry-join=consul-server1 -retry-join=consul-server2"
    volumes:
      - ./data/data3:/consul/data
    networks:
      - consul-net
    restart: always

networks:
  consul-net:
    external: true
