version: "3.1"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.1
    environment:
      - cluster.name=nilsir-es
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - ${ES_HTTP_PORT:-9200}:9200
      - ${ES_TCP_PORT:-9300}:9300
    restart: always
    volumes:
      - ./data:/usr/share/elasticsearch/data
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.1.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - ${KIBANA_PORT:-5601}:5601
    restart: always
networks:
  es-net:
    external: true
