version: '3.1'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}:rw
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./log:/var/log/nginx:rw
    restart: always
    networks:
      - nginx-net

networks:
  nginx-net:
    # external: true