version: "3.1"

services:
    mysql:
        container_name: "mysql"
        image: mysql:5.7.33
        ports:
            - "${MYSQL_PORT:-3306}:3306"
        volumes:
            - ./log:/logs/:rw
            - ./data:/var/lib/mysql/:rw
            - ./conf:/etc/mysql/conf.d/:rw
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-nilsir}
        restart: always
        networks:
            - mysql-net

networks:
    mysql-net:
        external: true
